version: '3.9'

services:
  postgres13_db1:
    image: postgres:13
    container_name: postgres13_db1
    ports:
      - "5432:5432"
#    jdbc:postgres13_db1://localhost:5433/db1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db1
      - POSTGRES_PASSWORD=0
    volumes:
      - postgres_data_db1:/var/lib/postgresql/data

volumes:
  postgres_data_db1: